2021-11-18T17:28:30+08:00	[31mERROR[0m	log/log.go:43	ping db failed	{"nameError": "json: unsupported type: func() string", "err": "driver: bad connection"}
2021-11-18T17:28:30+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:28:35+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:28:40+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:28:45+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:28:50+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:28:55+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"nameError": "json: unsupported type: func() string"}
2021-11-18T17:29:00+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"nameError": "json: unsupported type: func() string"}
2021-11-18T17:29:05+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"nameError": "json: unsupported type: func() string"}
2021-11-18T17:32:55+08:00	[31mERROR[0m	log/log.go:43	ping db failed	{"nameError": "json: unsupported type: func() string", "err": "driver: bad connection"}
2021-11-18T17:32:55+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:33:00+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:33:05+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:33:10+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:33:15+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:33:28+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"nameError": "json: unsupported type: func() string"}
2021-11-18T17:38:36+08:00	[31mERROR[0m	log/log.go:43	ping db failed	{"nameError": "json: unsupported type: func() string", "err": "driver: bad connection"}
2021-11-18T17:38:36+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:38:41+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:38:46+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"nameError": "json: unsupported type: func() string", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:38:51+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"nameError": "json: unsupported type: func() string"}
2021-11-18T17:38:56+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"nameError": "json: unsupported type: func() string"}
2021-11-18T17:39:01+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"nameError": "json: unsupported type: func() string"}
2021-11-18T17:39:06+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"nameError": "json: unsupported type: func() string"}
2021-11-18T17:39:11+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"nameError": "json: unsupported type: func() string"}
2021-11-18T17:39:16+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"nameError": "json: unsupported type: func() string"}
2021-11-18T17:41:14+08:00	[31mERROR[0m	log/log.go:43	ping db failed	{"name": "default_client", "err": "driver: bad connection"}
2021-11-18T17:41:14+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:41:19+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:41:24+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"name": "default_client"}
2021-11-18T17:41:29+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"name": "default_client"}
2021-11-18T17:41:34+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"name": "default_client"}
2021-11-18T17:41:39+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"name": "default_client"}
2021-11-18T17:43:18+08:00	[31mERROR[0m	log/log.go:43	ping db failed	{"name": "default_client", "err": "driver: bad connection"}
2021-11-18T17:44:14+08:00	[31mERROR[0m	log/log.go:43	ping db failed	{"name": "default_client", "err": "driver: bad connection"}
2021-11-18T17:44:14+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:44:19+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:44:24+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:44:29+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"name": "default_client"}
2021-11-18T17:44:34+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"name": "default_client"}
2021-11-18T17:44:39+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"name": "default_client"}
2021-11-18T17:44:44+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"name": "default_client"}
2021-11-18T17:47:10+08:00	[31mERROR[0m	log/log.go:43	ping db failed	{"name": "default_client", "err": "driver: bad connection"}
2021-11-18T17:47:18+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:47:23+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:47:28+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:47:28+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:47:30+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:47:35+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: failed to receive message (unexpected EOF)"}
2021-11-18T17:52:16+08:00	[31mERROR[0m	log/log.go:43	ping db failed	{"name": "default_client", "err": "driver: bad connection"}
2021-11-18T17:52:16+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:52:21+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:52:26+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"name": "default_client"}
2021-11-18T17:52:36+08:00	[31mERROR[0m	log/log.go:43	ping db failed	{"name": "default_client", "err": "driver: bad connection"}
2021-11-18T17:52:36+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:52:41+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:52:46+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: failed to receive message (unexpected EOF)"}
2021-11-18T17:52:51+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"name": "default_client"}
2021-11-18T17:53:29+08:00	[31mERROR[0m	log/log.go:43	ping db failed	{"name": "default_client", "err": "driver: bad connection"}
2021-11-18T17:53:29+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:53:34+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:53:39+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:53:44+08:00	[31mERROR[0m	log/log.go:43	recover db failed	{"name": "default_client", "err": "failed to connect to `host=127.0.0.1 user=postgres database=evolve`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}
2021-11-18T17:53:49+08:00	[31mERROR[0m	log/log.go:43	recover db successful	{"name": "default_client"}
